// Generates the <script type="importmap"> that lets Blob-URL-loaded plugins
// resolve bare "react"/"react-dom"/etc. specifiers to the exact same module
// instance the host app itself uses - critical so hooks work (two separate
// React instances break hooks). See docs/architecture-plan.md "Plugin loading
// mechanism" for why this can't just be a hand-written static path:
// - Dev: Vite's dependency pre-bundler serves react at a stable filename but
//   cache-busts it with a `?v=<hash>` query that changes per optimize run, so
//   the exact URL must be read from node_modules/.vite/deps/_metadata.json.
// - Build: react/react-dom get bundled into content-hashed chunk files, so the
//   exact URL must be read from the Rollup output bundle after it's built.
//
// Extra bare specifiers (e.g. spike-dep) can be merged in via `extraImports`
// so only one <script type="importmap"> ever exists in the document (a
// second one is a spec violation the browser will reject).
import { createRequire } from "node:module";
import type { Plugin } from "vite";

const requirePkg = createRequire(import.meta.url);

// Maps each specifier the import map must cover to the name of the facade
// entry (see src/host/vendor-entries/) that the build's rollupOptions.input
// must also declare, so its emitted chunk can be located here.
const BUILD_SPECIFIER_TO_ENTRY_NAME: Record<string, string> = {
  react: "vendor-react",
  "react-dom": "vendor-react-dom",
  "react-dom/client": "vendor-react-dom-client",
  "react/jsx-runtime": "vendor-react-jsx-runtime",
};

// Maps each vendor-entry facade file (see src/host/vendor-entries/) to the bare
// specifier it must re-export. Those files are deliberately empty on disk; their
// real body is generated by the `load` hook below.
const VENDOR_ENTRY_SPECIFIERS: Record<string, string> = {
  "react.ts": "react",
  "react-dom.ts": "react-dom",
  "react-dom-client.ts": "react-dom/client",
  "react-jsx-runtime.ts": "react/jsx-runtime",
};

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

export function reactImportMapPlugin(extraImports: Record<string, string> = {}): Plugin {
  return {
    name: "stewrd-react-importmap",

    // react/react-dom ship as CommonJS. Rolldown (Vite 8's bundler) wraps a CJS
    // dependency in a lazy `require_react()` factory and the shared chunk
    // exports only that factory - the individual export names are not statically
    // known. A star re-export (`export * from "react"`) therefore resolves to
    // *zero* named exports and the facade's entry chunk is emitted with no
    // `export` statement at all, making it useless as an import-map target.
    // (This is a CJS-interop limitation, not tree-shaking, which is why
    // `preserveEntrySignatures: "strict"` alone made no difference: the
    // signature was faithfully preserved - it was simply empty. That option is
    // still required in vite.config.ts, to stop the minifier tree-shaking the
    // generated exports back off again.)
    //
    // Fix: rewrite each facade into an explicit named re-export list, read from
    // the real package at build time so it can never go stale on a React
    // upgrade. Rolldown resolves those names through the same shared chunk's
    // memoised `require_react()`, so the facade exposes the host's exact React
    // instance rather than a second bundled copy.
    load(id) {
      const file = id.replace(/\\/g, "/").split("?")[0];
      const match = /\/src\/host\/vendor-entries\/([^/]+)$/.exec(file);
      const specifier = match && VENDOR_ENTRY_SPECIFIERS[match[1]];
      if (!specifier) return null;

      const names = Object.keys(requirePkg(specifier)).filter((name) => IDENTIFIER.test(name));
      return `export { ${names.join(", ")} } from ${JSON.stringify(specifier)};\n`;
    },

    transformIndexHtml: {
      order: "post",
      handler(_html, ctx) {
        const imports: Record<string, string> = { ...extraImports };

        if (ctx.server) {
          // Do NOT point directly at Vite's raw pre-bundled dep chunk (e.g.
          // /node_modules/.vite/deps/react.js): that file is CJS-interop'd
          // into a bare `export default require_react()`, no named exports -
          // `import { useState } from "react"` only works in *app* source
          // because Vite's transform pipeline rewrites the CONSUMER's import
          // statement, not because the dep chunk itself has real exports.
          // Instead point at the same vendor-entries facade this plugin's
          // `load` hook fills in below - Vite's normal dev transform pipeline
          // applies that same CJS-interop rewriting to the facade's generated
          // `export { useState, ... } from "react"` line, so the facade's
          // OWN served URL ends up with real named exports. This mirrors the
          // production path exactly, just via dev transform instead of a
          // Rolldown chunk.
          for (const [file, specifier] of Object.entries(VENDOR_ENTRY_SPECIFIERS)) {
            imports[specifier] = `/src/host/vendor-entries/${file}`;
          }
        }
        if (ctx.bundle) {
          for (const [fileName, chunk] of Object.entries(ctx.bundle)) {
            if (chunk.type !== "chunk" || !chunk.isEntry) continue;
            for (const [spec, entryName] of Object.entries(BUILD_SPECIFIER_TO_ENTRY_NAME)) {
              if (chunk.name === entryName) imports[spec] = `/${fileName}`;
            }
          }
        }

        return [
          {
            tag: "script",
            attrs: { type: "importmap" },
            injectTo: "head-prepend",
            children: JSON.stringify({ imports }),
          },
        ];
      },
    },
  };
}
